services:
  socializer-db:
    image: mongo:8.0-rc
    container_name: socializer-db
    env_file:
      - ./.env
    volumes:
      - ./db:/data/db
      - ./init-db-scripts:/docker-entrypoint-initdb.d
